# Generated by Django 3.0.4 on 2020-07-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='product',
        ),
    ]
