# Generated by Django 3.0.8 on 2020-07-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
